version: "3.8"

services:
  mongodb:
    container_name: catalog-mongodb
    image: mongo
    ports:
      - "27017:27017"
    restart: always
    volumes:
      - ./data/db:/data/db

  api:
    container_name: catalog-api
    image: node:18
    working_dir: /usr/src/app
    restart: always # Policy applied to the container termination
    environment:
      - MONGO_URL=mongodb://mongodb:27017/catalog
    volumes: # Defines the volume to be mounted in the container
      - ./package.json:/usr/src/app/package.json
      - ./yarn.lock:/usr/src/app/yarn.lock
      - ./dist:/usr/src/app/dist
    ports: # Exposes container ports to the host
      - "3000:3000"
    command: bash -c "npm install && npm run dev"
    links: # Links the container to another container using a network alias
      - mongodb
    depends_on: # Defines the dependencies of the container
      - mongodb
